---
- name: Converge
  hosts: all
  become: true
  gather_facts: false
  vars:
    db_host: "localhost"
    vault_db_password: "test-password"
  pre_tasks:
    - name: Install Python for Ansible
      ansible.builtin.raw: apt-get update && apt-get install -y python3
      changed_when: true

  tasks:
    - name: Apply database role
      ansible.builtin.include_role:
        name: ../../..
        apply:
          tags:
            - always
      tags:
        - always
