---
all:
  children:
    app:
      hosts:
        app1:
          ansible_host: 15.237.189.244
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/devops_s8
          ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
        app2:
          ansible_host: 13.37.255.197
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/devops_s8
          ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
